forge "http://forge.puppetlabs.com"

mod 'puppetlabs/stdlib'
mod 'puppetlabs/apt'

mod 'vagrant',
  :git => '/home/jwedgeco/veewee/boxes/modules.local/vagrant'

mod 'edgester/kerberos',
  :git => 'git://github.com/edgester/puppet-kerberos.git'

mod 'edgester/openafs',
  :git => 'git://github.com/edgester/puppet-openafs.git'
