forge "http://forge.puppetlabs.com"

mod 'puppetlabs/stdlib'
mod 'puppetlabs/apt'

mod 'vagrant',
  :git => 'git://github.com/edgester/puppet-module-vagrant.git'

mod 'edgester/kerberos',
  :git => 'git://github.com/edgester/puppet-module-kerberos.git'

mod 'edgester/openafs',
  :git => 'git://github.com/edgester/puppet-module-openafs.git'
