forge "http://forge.puppetlabs.com"

mod 'puppetlabs/stdlib'
mod 'puppetlabs/apt'

mod 'vagrant',
  :git => '/home/jwedgeco/veewee/boxes/modules.local/vagrant'

mod 'edgester/kerberos',
  :git => '/home/jwedgeco/veewee/boxes/modules.local/kerberos'

mod 'edgester/openafs',
  :git => '/home/jwedgeco/veewee/boxes/modules.local/openafs'
